# -*- coding: utf-8 -*-
"""task 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvxUJiSdFI5u-AxOrAICa83UcOeJOdm8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/StudentsPerformance_preprocessed.csv')

df.head()

print(df.columns)

avg_scores = df.groupby(
    ['parental level of education', 'lunch']
)[['math score', 'reading score', 'writing score']].mean().reset_index()

avg_scores.plot(
    x='parental level of education',
    y=['math score', 'reading score', 'writing score'],
    kind='bar',
    figsize=(12,6)
)

plt.title('Average Scores by Parental Education and Lunch Type')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.legend(title='Subject')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    data=df,
    x='test preparation course',
    y='math score'
)

plt.title('Math Score Variance by Test Preparation')
plt.xlabel('Test Preparation')
plt.ylabel('Math Score')
plt.show()

plt.figure(figsize=(12,6))

sns.boxplot(
    data=df,
    x='test preparation course',
    y='writing score'
)

plt.title('Writing Score Variance by Test Preparation')
plt.xlabel('Test Preparation')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(12,6))

sns.boxplot(
    data=df,
    x='test preparation course',
    y='reading score'
)

plt.title('Reading Score Variance by Test Preparation')
plt.xlabel('Test Preparation')
plt.ylabel('Reading Score')
plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x='math score',
    y='reading score'
)

plt.title('Math Score vs Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x='math score',
    y='writing score'
)

plt.title('Math Score vs Writing Score')
plt.xlabel('Math Score')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x='reading score',
    y='writing score'
)

plt.title('Reading Score vs Writing Score')
plt.xlabel('Reading Score')
plt.ylabel('Writing Score')
plt.show()

scores = df[['math score', 'reading score', 'writing score']]

plt.figure(figsize=(8,6))

sns.heatmap(
    scores.corr(),
    annot=True,
    cmap='coolwarm',
    linewidths=0.5
)

plt.title('Correlation Between Student Scores')
plt.show()

print("Average scores by lunch type:")
print(df.groupby('lunch')[['math score',
                           'reading score',
                           'writing score']].mean())

print("\nAverage scores by test preparation:")
print(df.groupby('test preparation course')[['math score',
                                             'reading score',
                                             'writing score']].mean())

print("\nAverage scores by parental education:")
print(df.groupby('parental level of education')[['math score',
                                                 'reading score',
                                                 'writing score']].mean())

print("Student Performance Visualization Completed")

print("\nDataset Shape:", df.shape)

print("\nAverage Scores:")
print(df[['math score',
          'reading score',
          'writing score']].mean())

print("\nCorrelation:")
print(df[['math score',
          'reading score',
          'writing score']].corr())

